all:
  vars:
    ansible_connection: ssh
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    app_servers:
      hosts:
        20.16.216.37:

    private_infrastructure:
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q azureuser@20.16.216.37"'
      children:
        kafka_brokers:
          hosts:
            10.0.2.20:
