Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.synced_folder "..", "/vagrant"

  # Kafka brokers
  (1..3).each do |i|
    config.vm.define "broker#{i}" do |node|
      node.vm.hostname = "broker#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"
    end
  end

  # App VM
  config.vm.define "app-server" do |app|
    app.vm.hostname = "app-server"
    app.vm.network "private_network", ip: "192.168.56.20"
  end

  # BDD VM
  config.vm.define "db-server" do |db|
    db.vm.network "private_network", ip: "192.168.56.30"
  end

  # Ansible Provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/playbooks/playbook.yml"
  end
end