server:
  port: 8080
spring:
  application:
    name: ai-analyzer-service
  ai:
    openai:
      base-url: https://openrouter.ai/api
      api-key: ${OPEN_ROUTER_API_KEY}
      chat:
        options:
          model: ${AI_MODEL:deepseek/deepseek-v3.2}
          temperature: 0.1
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    listener:
      concurrency: ${KAFKA_CONCURRENCY:1}
    consumer:
      group-id: analyzer-group
      auto-offset-reset: earliest
      # On utilise le wrapper d'erreur de Spring
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.jobstream.dto"
        # si la désérialisation échoue, on ne crash pas
        spring.deserializer.value.retryable: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        acks: all
        retries: 3
app:
  kafka:
    topics:
      consumer-topic: job-to-analyzed
      producer-topic: analyzed-jobs
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true