all:
  children:
    brokers:
      hosts:
        broker1:
          ansible_host: 192.168.56.11
        broker2:
          ansible_host: 192.168.56.12
        broker3:
          ansible_host: 192.168.56.13
    db:
      hosts:
        db-server:
          ansible_host: 192.168.56.30
    app:
      hosts:
        app-server:
          ansible_host: 192.168.56.20