spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5433/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# Adzuna API configuration
adzuna:
  api:
    base-url: https://api.adzuna.com/v1/api
    app-id: ${ADZUNA_APP_ID:}
    app-key: ${ADZUNA_APP_KEY:}
    default-country: ${ADZUNA_DEFAULT_COUNTRY:ch}