name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Format the repository name in lowercase.
        id: string
        run: |
          echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build and push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: codebase/dashboard-service/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.string.outputs.repo }}/dashboard-service:latest

      - name: Build and push ai-analyzer Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: codebase/ai-analyzer-service/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.string.outputs.repo }}/ai-analyzer-service:latest

      - name: Build and push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: codebase/jobstream-frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.string.outputs.repo }}/frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max