name: Manual deploy
on:
  workflow_dispatch:

jobs:
  deploy-to-azure:
    name: Deployment on Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.5"

      - name: Connection to Azure for Terraform
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          echo "${{ secrets.AZURE_VM_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Configure password Ansible vault
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass

      - name: Terraform Init & Apply
        run: |
          cd infra/azure_with_terraform_ansible/terraform/
          terraform init
          terraform apply -auto-approve

      - name: Run Ansible playbook
        run: |
          pip install ansible
          ansible-playbook -i hosts.yml playbook.yml --vault-password-file .vault_pass

      - name: Delete temp files
        if: always()
        run: |
          rm -f .vault_pass